#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <math.h>

#include "PolicyReplacement.h"
#include "PolicyWrite.h"

// App config
#define APP_NAME "NuCachis"
#define APP_DESC "NuCachis. A simple, interactive cache simulator"
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define MAX_PATH_LENGTH 512

// Simulator config
#define MAX_CACHE_LEVELS 5

// Simulator configuration. Used to pass config to the Simulator's constructor from the config file
typedef struct {
    // CPU configs
    int32_t cpuAddressWidth, cpuWordWidth, cpuRandSeed;

    // Memory configs
    double memAccessTimeSingle, memAccessTimeBurst;
    int64_t memSize, memPageSize, memPageBaseAddress;

    // Cache configs
    int64_t cacheSize[MAX_CACHE_LEVELS];
    int64_t cacheLineSize[MAX_CACHE_LEVELS];
    double cacheAccessTime[MAX_CACHE_LEVELS];
    uint8_t cacheAssoc[MAX_CACHE_LEVELS];
    bool cacheIsSplit[MAX_CACHE_LEVELS];
    PolicyWrite cachePolicyWrite[MAX_CACHE_LEVELS];
    PolicyReplacement cachePolicyReplacement[MAX_CACHE_LEVELS];
    

    // Other misc configs
    uint32_t miscNumOperations;
    uint8_t miscCacheLevels;
} SimulatorConfig;

// The type of operation that an instruction will represent
typedef enum {
    LOAD,
    STORE,
    NUM_OPERATION_TYPES
} Operation;

// The memory operation that will be generated by an instruction or a cache.
typedef struct {
    uint64_t data, address;
    Operation operation;
    bool isData;              // Instruction or data
    bool hasBreakPoint;
} MemoryOperation;

typedef struct {
    double totalTime;         // The total time to complete the request
    uint64_t* data;           // Pointer to the data that has been requested
    uint32_t numWords;        // The number of requested words
} MemoryReply;

/* Global variables */
extern int debugLevel;

/* Misc parsing functions */
// Policy parsing functions
const char* replacementPolicyStr(PolicyReplacement policy);
const char* writePolicyStr(PolicyWrite policy);

// General parse functions
long parseLong(const char* string, bool base2);
int parseBoolean(const char * string);
int parseInt(const char * string);
int parseReplacementPolicy(const char * string);
int parseWritePolicy(const char * string);
double parseDouble(const char * string);
long parseAddress(const char* pageBaseAddress);

// Checking functions
bool isPowerOf2(long number);
bool isAMultipleOf8(long number);
bool isCorrectBinary(const char* string);
bool isCorrectHexadecimal(char* number);
bool isCorrectDecimal(char* number);

// Conversion functions
void contentArrayToString(unsigned* array, char* content, int count, int width);
void contentStringToArray(unsigned* array, char* content, int level);

/* Other Functions */
// DRAMSys functions
int openDramsysFile(const char* filename, FILE** f);
void writeToDramsysFile(FILE** f, int lastNumber, int readOrWrite, int address);
void close_dramsys_file(FILE **f);

// Misc Functions
int countLines(FILE* fp);
int cycle_rand();
