#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

#include "PolicyReplacement.h"
#include "PolicyWrite.h"

// App config
#define APP_NAME "NuCachis"
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define MAX_PATH_LENGTH 512

// Simulator config
#define MAX_CACHE_LEVELS 5

// File paths for the trace and config
static char configPath[MAX_PATH_LENGTH];
static char tracePath[MAX_PATH_LENGTH];

// The type of operation that an instruction will represent
typedef enum {
    LOAD,
    STORE,
    NUM_OPERATION_TYPES
} Operation;

// The memory operation that will be generated by an instruction or a cache.
typedef struct {
  uint64_t data, address;
  Operation operation;
  bool isData;              // Instruction or data
  bool hasBreakPoint;
  //int size;
} MemoryOperation;

/* Global variables */
extern int debugLevel;

/* Misc parsing functions */
// Policy parsing functions
const char* replacementPolicyStr(PolicyReplacement policy);
const char* writePolicyStr(PolicyWrite policy);

// General parse functions
long parseLong(const char* string, bool base2);
int parseBoolean(const char * string);
int parseInt(const char * string);
int parseReplacementPolicy(const char * string);
int parseWritePolicy(const char * string);
double parseDouble(const char * string);
long parseAddress(const char* pageBaseAddress);

// Checking functions
bool isPowerOf2(long number);
bool isAMultipleOf8(long number);
bool isCorrectBinary(const char* string);
bool isCorrectHexadecimal(char* number);
bool isCorrectDecimal(char* number);

// Conversion functions
void contentArrayToString(unsigned* array, char* content, int count, int width);
void contentStringToArray(unsigned* array, char* content, int level);

/* Other Functions */
// DRAMSys functions
int openDramsysFile(const char* filename, FILE** f);
void writeToDramsysFile(FILE** f, int lastNumber, int readOrWrite, int address);
void close_dramsys_file(FILE **f);

// Misc Functions
int countLines(FILE* fp);
int cycle_rand();
